// ──────────────────────────────────────────────────────────────
// Generates: src/schemas/<entity>.schema.ts
//
// Zod validation schemas for:
//   - create (insert) operations
//   - update (partial) operations
//   - query params (pagination + filters + search)
// Plus inferred TypeScript types from each schema.
// ──────────────────────────────────────────────────────────────

import type { GeneratorContext, ParsedColumn } from "../parser/types.js";

export function generateSchema(ctx: GeneratorContext): string {
  const { table, pascalSingular } = ctx;

  const createFields = table.columns.filter(
    (c) => !c.isAutoGenerated && !c.isPrimaryKey
  );
  const filterableColumns = table.columns.filter(
    (c) => !c.isAutoGenerated || c.isPrimaryKey
  );

  const lines: string[] = [];

  lines.push(`import { z } from "zod";`);
  lines.push(``);

  // ── Create schema ──
  lines.push(`// ── Create ──────────────────────────────────────────────────`);
  lines.push(`export const create${pascalSingular}Schema = z.object({`);
  for (const col of createFields) {
    lines.push(`  ${col.name}: ${buildZodType(col)},`);
  }
  lines.push(`});`);
  lines.push(``);

  // ── Update schema ──
  lines.push(`// ── Update (partial) ────────────────────────────────────────`);
  lines.push(`export const update${pascalSingular}Schema = create${pascalSingular}Schema.partial().refine(`);
  lines.push(`  (data) => Object.keys(data).length > 0,`);
  lines.push(`  { message: "At least one field must be provided for update" }`);
  lines.push(`);`);
  lines.push(``);

  // ── Query schema ──
  lines.push(`// ── Query params (pagination + filters) ─────────────────────`);
  lines.push(`export const query${pascalSingular}Schema = z.object({`);
  lines.push(`  page: z.coerce.number().int().positive().default(1),`);
  lines.push(`  limit: z.coerce.number().int().positive().max(100).default(20),`);
  lines.push(`  sort: z.string().optional(),`);
  lines.push(`  order: z.enum(["asc", "desc"]).default("asc"),`);
  lines.push(`  search: z.string().optional(),`);

  for (const col of filterableColumns) {
    if (col.isPrimaryKey || col.references || col.enumValues || col.drizzleType === "boolean") {
      lines.push(`  ${col.name}: ${buildFilterZodType(col)}.optional(),`);
    }
  }

  lines.push(`});`);
  lines.push(``);

  // ── Type exports ──
  lines.push(`// ── Inferred types ──────────────────────────────────────────`);
  lines.push(`export type Create${pascalSingular}Input = z.infer<typeof create${pascalSingular}Schema>;`);
  lines.push(`export type Update${pascalSingular}Input = z.infer<typeof update${pascalSingular}Schema>;`);
  lines.push(`export type Query${pascalSingular}Input = z.infer<typeof query${pascalSingular}Schema>;`);
  lines.push(``);

  return lines.join("\n");
}

// ── Zod type builders (unchanged logic) ─────────────────────

function buildZodType(col: ParsedColumn): string {
  let schema = baseZodType(col);

  if (col.isNotNull && !col.hasDefault) {
    // required — no modifier
  } else if (!col.isNotNull) {
    schema += `.nullable().optional()`;
  } else if (col.hasDefault) {
    schema += `.optional()`;
  }

  return schema;
}

function baseZodType(col: ParsedColumn): string {
  if (col.enumValues && col.enumValues.length > 0) {
    const vals = col.enumValues.map((v) => `"${v}"`).join(", ");
    return `z.enum([${vals}])`;
  }
  if (col.isArray) {
    return `z.array(${scalarZodType(col)})`;
  }
  return scalarZodType(col);
}

function scalarZodType(col: ParsedColumn): string {
  switch (col.drizzleType) {
    case "serial":
    case "smallserial":
    case "bigserial":
    case "integer":
    case "smallint":
    case "int":
    case "bigint":
      return "z.number().int()";
    case "real":
    case "doublePrecision":
      return "z.number()";
    case "numeric":
    case "decimal":
      return `z.string().regex(/^-?\\d+(\\.\\d+)?$/, "Must be a valid decimal")`;
    case "text":
      return "z.string()";
    case "varchar":
    case "char":
      return col.maxLength ? `z.string().max(${col.maxLength})` : "z.string()";
    case "boolean":
      return "z.boolean()";
    case "uuid":
      return "z.string().uuid()";
    case "date":
      return `z.string().regex(/^\\d{4}-\\d{2}-\\d{2}$/, "Expected YYYY-MM-DD")`;
    case "time":
      return "z.string()";
    case "timestamp":
      return "z.coerce.date()";
    case "interval":
      return "z.string()";
    case "json":
    case "jsonb":
      return "z.unknown()";
    case "inet":
    case "cidr":
    case "macaddr":
    case "macaddr8":
      return "z.string()";
    case "pgEnum":
      if (col.enumValues && col.enumValues.length > 0) {
        const vals = col.enumValues.map((v) => `"${v}"`).join(", ");
        return `z.enum([${vals}])`;
      }
      return "z.string()";
    default:
      return "z.unknown()";
  }
}

function buildFilterZodType(col: ParsedColumn): string {
  if (col.enumValues && col.enumValues.length > 0) {
    const vals = col.enumValues.map((v) => `"${v}"`).join(", ");
    return `z.enum([${vals}])`;
  }
  switch (col.tsType) {
    case "number":
      return "z.coerce.number()";
    case "boolean":
      return "z.coerce.boolean()";
    default:
      return "z.string()";
  }
}
