// ──────────────────────────────────────────────────────────────
// Parsed schema types — the intermediate representation between
// Drizzle schema AST and code generation templates.
// ──────────────────────────────────────────────────────────────

export interface ParsedColumn {
  /** Property name in the Drizzle schema (camelCase) */
  name: string;
  /** Column name in the database (snake_case) */
  dbName: string;
  /** Drizzle column type function name: serial, varchar, text, integer, boolean, etc. */
  drizzleType: string;
  /** Inferred TypeScript type: string, number, boolean, Date, unknown, etc. */
  tsType: string;
  /** Whether this column is the (or part of the) primary key */
  isPrimaryKey: boolean;
  /** NOT NULL constraint */
  isNotNull: boolean;
  /** UNIQUE constraint */
  isUnique: boolean;
  /** Has a .default() or .defaultNow() or .$defaultFn() */
  hasDefault: boolean;
  /** Raw default expression string if detected */
  defaultExpression: string | null;
  /** References another table (foreign key) */
  references: ForeignKeyRef | null;
  /** Enum values if this column uses a pgEnum */
  enumValues: string[] | null;
  /** Enum variable name in the schema */
  enumName: string | null;
  /** varchar/char max length if specified */
  maxLength: number | null;
  /** Whether this is an array column */
  isArray: boolean;
  /** Whether this column is auto-generated (serial, identity, etc.) */
  isAutoGenerated: boolean;
  /** Whether this looks like a timestamp column (createdAt/updatedAt) */
  isTimestamp: boolean;
  /** Full modifier chain text for debugging */
  rawChain: string;
}

export interface ForeignKeyRef {
  /** Referenced table variable name */
  table: string;
  /** Referenced column name */
  column: string;
}

export interface ParsedRelation {
  /** Relation name (e.g., "posts", "author") */
  name: string;
  /** Relation type: "one" or "many" */
  type: "one" | "many";
  /** Referenced table variable name */
  referencedTable: string;
  /** Fields and references for "one" relations */
  fields: string[];
  references: string[];
}

export interface ParsedEnum {
  /** Variable name in the schema */
  variableName: string;
  /** Enum name in the database */
  dbName: string;
  /** Enum values */
  values: string[];
}

export interface ParsedTable {
  /** Variable name exported from schema (e.g., "users") */
  variableName: string;
  /** Table name in the database (e.g., "users") */
  dbName: string;
  /** All columns */
  columns: ParsedColumn[];
  /** Relations defined for this table */
  relations: ParsedRelation[];
  /** Primary key column names */
  primaryKeyColumns: string[];
  /** Whether this table has soft delete (deletedAt/isDeleted/status columns) */
  hasSoftDelete: boolean;
  /** The soft-delete column name if detected */
  softDeleteColumn: string | null;
  /** Text columns eligible for search (ilike) */
  searchableColumns: string[];
  /** Foreign key columns for relationship filtering */
  foreignKeyColumns: ParsedColumn[];
}

export interface ParsedSchema {
  /** All enums found */
  enums: ParsedEnum[];
  /** All tables found */
  tables: ParsedTable[];
  /** Raw import path of the schema file (for generated imports) */
  schemaPath: string;
}

// ──────────────────────────────────────────────────────────────
// Generator context — passed to each code generator
// ──────────────────────────────────────────────────────────────

export interface GeneratorContext {
  table: ParsedTable;
  schema: ParsedSchema;
  /** Singular name: "user" */
  singular: string;
  /** Plural name: "users" */
  plural: string;
  /** PascalCase singular: "User" */
  pascalSingular: string;
  /** PascalCase plural: "Users" */
  pascalPlural: string;
  /** camelCase singular: "user" */
  camelSingular: string;
  /** camelCase plural: "users" */
  camelPlural: string;
  /** Module folder name: "users" */
  moduleName: string;
  /** Relative path from module to schema: "../../db/schema" */
  schemaImportPath: string;
  /** Relative path from module to db: "../../db" */
  dbImportPath: string;
}
